import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Frontend Mentor Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-3xl font-bold underline border border-white">
        Frontend Mentor Project
      </h1>
      <Link href='/stats_preview_card_component'><h2>Stats Preview Card Component</h2></Link>
      <Link href='/qr_code_component'><h2>QR Code Component</h2></Link>
      <Link href='/results_summary_component'><h2>Results Summary Component</h2></Link>
      <Link href='/single_page_design_portfolio'><h2>Single Page Design Portfolio</h2></Link>
      <Link href='/myteam-multi-page-website'><h2>Myteam Multi-page Website</h2></Link>
      
    </>
  )
}
